name: Floorsheet Data Auto Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 11 * * *'  # Runs at 11:30 AM UTC (5:15 PM Nepal Time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python scrape_nepse.py

      - name: Commit and Push
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}  # Secure authentication using GitHub Secrets
        run: |
          git config --local user.email "bhupen339473@gmail.com"
          git config --local user.name "bhupennn"
          git add .
          git commit -am "Updated floorsheet data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/bhupennn/Bhupenra.git main
